#!/bin/sh

. "${XDG_CONFIG_HOME-$HOME/.config}/khald/config"

while true; do
    if [ "$(khal list now "$NOTIFY_INTERVAL" --day-format='')" != "No events" ]; then
        notify-send \
            -i /usr/share/icons/Adwaita/96x96/mimetypes/x-office-calendar-symbolic.symbolic.png \
            -h string:x-canonical-private-synchronous:khald \
            "Events for Today, $(date '+%A, %B %d, %Y')" \
            "$(khal list now "$NOTIFY_INTERVAL" --format "{start-time} - {end-time}: [{calendar}] {title}" --day-format='')"
    fi
    sleep "$REFRESH_INTERVAL"
done
